# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'
    - name: Repository 
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
      # ID of the service to deploy
        service-id: srv-cnsa1m0cmk4c73alog8g
      # A Render API key
        api-key: rnd_2LOvACGrwmagFVuxvQeaWu2HAV48
    - name: Install dependencies    
      run: npm install
    - name: run start
      run: npm run start
    - name: start server
      run: node ./server/server.js
