# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: 
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
      # ID of the service to deploy
        service-id: srv-cnsa1m0cmk4c73alog8g
      # A Render API key
        api-key: rnd_2LOvACGrwmagFVuxvQeaWu2HAV48
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
